#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = examples
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/utils.js:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/utils.js
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/xdc.tci:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/xdc.tci
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/template.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/template.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/om2.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/om2.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/xmlgen.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/xmlgen.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/xmlgen2.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/xmlgen2.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/Warnings.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/Warnings.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/IPackage.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/IPackage.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/package.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/package.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/services/global/Clock.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/services/global/Clock.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/services/global/Trace.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/services/global/Trace.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/bld.js:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/bld.js
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/BuildEnvironment.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/PackageContents.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/PackageContents.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/_gen.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/_gen.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Library.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Library.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Executable.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Executable.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Repository.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Repository.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Configuration.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Configuration.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Script.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Script.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Manifest.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Manifest.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Utils.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/Utils.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget2.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget2.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget3.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITarget3.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/ITargetFilter.xs
/db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/package.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-v06/product/xdccore/Linux/xdctools_3_32_00_06_core/packages/xdc/bld/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/tirtos.bld:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/tirtos.bld
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/targets/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/targets/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/targets/C28_large.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/targets/C28_large.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/targets/C28_float.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/targets/C28_float.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/targets/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/targets/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/targets/arm/elf/IArm.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/targets/arm/elf/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/targets/arm/elf/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/iar/targets/arm/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/iar/targets/arm/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/iar/targets/arm/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/iar/targets/arm/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/_utils.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/_utils.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/Linux86.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/Linux86.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/Mingw.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/Mingw.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/GCArmv6.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/GCArmv7A.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/IM.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/IM.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/M3.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/M3.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/M4.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/M4.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/M4F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/M4F.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/A8F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/A8F.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/A9F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/A9F.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/A15F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/A15F.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/A53F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/A53F.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/gnu/targets/arm/package.xs
package.mak: package.bld
package.mak: productList.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/tidrivers_cc13xx_cc26xx_2_21_01_01/packages/ti/drivers/xdcArgParser.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/tidrivers_cc13xx_cc26xx_2_21_01_01/packages/ti/drivers/xdcArgParser.xs
package.mak: Boards.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/tidrivers_cc13xx_cc26xx_2_21_01_01/packages/ti/drivers/msp43xOptions.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/tidrivers_cc13xx_cc26xx_2_21_01_01/packages/ti/drivers/msp43xOptions.xs
/db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/sysbios/examples/TargetOptions.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-o08/exports/tirtos_cc13xx_cc26xx_2_21_01_08/products/bios_6_46_01_38/packages/ti/sysbios/examples/TargetOptions.xs
package.mak: ExampleList.xs
endif

all,em3 clean,em3 .libraries,em3 .dlls,em3 .executables,em3 test,em3:;
all,rm3 clean,rm3 .libraries,rm3 .dlls,rm3 .executables,rm3 test,rm3:;
all,m3g clean,m3g .libraries,m3g .dlls,m3g .executables,m3g test,m3g:;

all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_examples.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package examples" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.cfg.xdc.inc: .interfaces $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js examples $@

test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,examples
ifeq (,$(MK_NOGENDEPS))
-include package/rel/examples.tar.dep
endif
package/rel/examples/examples/package/package.rel.xml: package/package.bld.xml
package/rel/examples/examples/package/package.rel.xml: package/build.cfg
package/rel/examples/examples/package/package.rel.xml: package/package.xdc.inc
package/rel/examples/examples/package/package.rel.xml: Boards.xs
package/rel/examples/examples/package/package.rel.xml: ExampleList.xs
package/rel/examples/examples/package/package.rel.xml: makefile.defs
package/rel/examples/examples/package/package.rel.xml: package.bld
package/rel/examples/examples/package/package.rel.xml: productList.xs
package/rel/examples/examples/package/package.rel.xml: ./source/display/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/display/display.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/display/splash_image.c
package/rel/examples/examples/package/package.rel.xml: ./source/display/splash_image.h
package/rel/examples/examples/package/package.rel.xml: ./source/display/display.c
package/rel/examples/examples/package/package.rel.xml: ./source/display/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/adcsinglechannel/lprf/adcsinglechannel.c
package/rel/examples/examples/package/package.rel.xml: ./source/adcsinglechannel/lprf/adcsinglechannel.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/adcsinglechannel/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/adcsinglechannel/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/adcbufcontinuous/lprf/adcBufContinuousSampling.c
package/rel/examples/examples/package/package.rel.xml: ./source/adcbufcontinuous/lprf/adcBufContinuousSampling.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/adcbufcontinuous/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/adcbufcontinuous/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/empty/lprf/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/empty/lprf/empty.c
package/rel/examples/examples/package/package.rel.xml: ./source/empty/lprf/empty.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/empty/lprf/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/empty_min/lprf/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/empty_min/lprf/empty_min.c
package/rel/examples/examples/package/package.rel.xml: ./source/empty_min/lprf/empty_min.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/empty_min/lprf/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/lcdSmartRF06EB/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/lcdSmartRF06EB/lcdSmartRF06EB.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/lcdSmartRF06EB/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/lcdSmartRF06EB/lcdSmartRF06EB.c
package/rel/examples/examples/package/package.rel.xml: ./source/pinInterrupt/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/pinInterrupt/pinInterrupt.c
package/rel/examples/examples/package/package.rel.xml: ./source/pinInterrupt/pinInterrupt.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/pinInterrupt/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/pinShutdown/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/pinShutdown/pinShutdown.c
package/rel/examples/examples/package/package.rel.xml: ./source/pinShutdown/pinShutdown.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/pinShutdown/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/pinStandby/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/pinStandby/pinStandby.c
package/rel/examples/examples/package/package.rel.xml: ./source/pinStandby/pinStandby.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/pinStandby/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/pwmled/lprf/pwmled.c
package/rel/examples/examples/package/package.rel.xml: ./source/pwmled/lprf/pwmled.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/pwmled/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/pwmled/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rf/rfExamples.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/rfpacket/tx/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfpacket/tx/rfPacketTx.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfpacket/tx/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1310/smartrf_settings.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1310/smartrf_settings.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/RFQueue.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/RFQueue.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfpacket/rx/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfpacket/rx/rfPacketRx.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfpacket/rx/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rfcarrierwave/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfcarrierwave/rfCarrierWave.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfcarrierwave/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rf/easylink/EasyLink.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/easylink/EasyLink.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfeasylink/tx/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfeasylink/tx/rfEasyLinkTx.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfeasylink/tx/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1310/smartrf_settings_predefined.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1310/smartrf_settings_predefined.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfeasylink/rx/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfeasylink/rx/rfEasyLinkRx.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfeasylink/rx/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rf/at/AtControl.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/at/AtControl.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/at/AtParams.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/at/AtParams.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/at/AtProcess.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/at/AtProcess.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/at/platform/inc/AtTerm.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/at/platform/tirtos/AtTerm.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/at/platform/tirtos/DbgPrint.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/at/platform/tirtos/PlatformTypes.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfeasylink/np/Per.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfeasylink/np/Per.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfeasylink/np/rfEasyLinkNp.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfeasylink/np/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfeasylink/np/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rfPacketErrorRate/menu.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfPacketErrorRate/config.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfPacketErrorRate/config.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfPacketErrorRate/menu.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfPacketErrorRate/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfPacketErrorRate/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rfPacketErrorRate/rfPacketErrorRate.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfPacketErrorRate/rx.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfPacketErrorRate/tx.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/RadioProtocol.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentrator/ConcentratorTask.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentrator/ConcentratorRadioTask.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentrator/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentrator/ConcentratorTask.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentrator/rfWsnConcentrator.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentrator/ConcentratorRadioTask.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentrator/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/SceAdc.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/SceAdc.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/node/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/node/NodeRadioTask.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/node/NodeTask.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/node/NodeTask.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/node/rfWsnNode.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/node/NodeRadioTask.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/node/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/dk/adc_sample.scp
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/dk/scif.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/dk/scif.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/dk/scif_framework.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/dk/scif_framework.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/dk/scif_osal_tirtos.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/dk/scif_osal_tirtos.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwakeonradio/tx/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfwakeonradio/tx/rfWakeOnRadioTx.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwakeonradio/tx/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rfwakeonradio/rx/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfwakeonradio/rx/rfWakeOnRadioRx.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwakeonradio/rx/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rfListenBeforeTalk/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfListenBeforeTalk/application_settings.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfListenBeforeTalk/application_settings.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfListenBeforeTalk/rfListenBeforeTalk.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfListenBeforeTalk/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/uartecho/lprf/uartecho.c
package/rel/examples/examples/package/package.rel.xml: ./source/uartecho/lprf/uartecho.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/uartecho/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/uartecho/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/benchloop/cc13xx_cc26xx/benchloop.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/benchloop/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/benchloop/benchloop.c
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/benchloop/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/bigtime/cc13xx_cc26xx/bigtime.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/bigtime/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/bigtime/bigtime.cpp
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/bigtime/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/clock/cc13xx_cc26xx/clock.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/clock/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/clock/clock.c
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/clock/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/error/cc13xx_cc26xx/error.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/error/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/error/error.c
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/error/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/hello/cc13xx_cc26xx/hello.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/hello/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/hello/hello.c
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/hello/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/memory/cc13xx_cc26xx/memory.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/memory/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/memory/memory.c
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/memory/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/mutex/cc13xx_cc26xx/mutex.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/mutex/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/mutex/mutex.c
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/mutex/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/semihost/cc13xx_cc26xx/semihost.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/semihost/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/semihost/semihost.c
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/semihost/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/swi/cc13xx_cc26xx/swi.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/swi/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/swi/swi.c
package/rel/examples/examples/package/package.rel.xml: ./source/kernel/swi/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/launchxl/adc_sample.scp
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/launchxl/scif.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/launchxl/scif.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/launchxl/scif_framework.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/launchxl/scif_framework.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/launchxl/scif_osal_tirtos.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/sce/launchxl/scif_osal_tirtos.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1350-lp/smartrf_settings.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1350-lp/smartrf_settings.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1350-lp/smartrf_settings_predefined.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1350-lp/smartrf_settings_predefined.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1350-lp/smartrf_settings_ble.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1350-lp/smartrf_settings_ble.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/rfDmExamples.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/rf/seb/SEB.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/seb/SEB.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/seb/SimpleBeacon.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/seb/SimpleBeacon.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/bim/BimFactoryReset.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/bim/BimFactoryReset.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/bim/ext_flash_layout.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentratordm/DmConcentratorTask.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentratordm/DmConcentratorRadioTask.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentratordm/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentratordm/DmConcentratorTask.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentratordm/rfWsnDmConcentrator.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentratordm/DmConcentratorRadioTask.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/concentratordm/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/nodedm/node_dk_luanchxl/DmNodeRadioTask.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/nodedm/node_dk_luanchxl/DmNodeTask.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/nodedm/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/nodedm/DmNodeRadioTask.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/nodedm/DmNodeTask.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/nodedm/rfWsnDmNode.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/nodedm/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/i2ctmp007/lprf/i2ctmp007.c
package/rel/examples/examples/package/package.rel.xml: ./source/i2ctmp007/lprf/i2ctmp007.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/i2ctmp007/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/i2ctmp007/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/pdmstream/README.md
package/rel/examples/examples/package/package.rel.xml: ./source/pdmstream/pdmstream.c
package/rel/examples/examples/package/package.rel.xml: ./source/pdmstream/pdmstream.cfg
package/rel/examples/examples/package/package.rel.xml: ./source/pdmstream/README.html
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1350-stk/smartrf_settings.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1350-stk/smartrf_settings.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1350-stk/smartrf_settings_predefined.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1350-stk/smartrf_settings_predefined.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1350-stk/smartrf_settings_ble.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc1350-stk/smartrf_settings_ble.h
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/nodedm/node_stk/DmNodeRadioTask.c
package/rel/examples/examples/package/package.rel.xml: ./source/rfwsn/nodedm/node_stk/DmNodeTask.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc2650/smartrf_settings.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc2650/smartrf_settings.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc2650/smartrf_settings_predefined.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc2650/smartrf_settings_predefined.h
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc2650/smartrf_settings_ble.c
package/rel/examples/examples/package/package.rel.xml: ./source/rf/smartrf_settings/cc2650/smartrf_settings_ble.h
package/rel/examples/examples/package/package.rel.xml: package/package.cfg.xdc.inc
package/rel/examples/examples/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

examples.tar: package/rel/examples.xdc.inc package/rel/examples/examples/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/examples.xdc.inc,package/rel/examples.tar.dep)


release release,examples: all examples.tar
clean:: .clean
	-$(RM) examples.tar
	-$(RM) package/rel/examples.xdc.inc
	-$(RM) package/rel/examples.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package


